### ISSUE TITLE
Gifv not downloading

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#197]
Hi, I have similar problem.
blog: multiboot2.tumblr.com
After I added blog and select to download everything it doesn't download first post with 2 gifs. Maybe something else also but there is a lot posts and didn't check everything.
Also I get wrong name with video in different post it has default name.
Reblogged both posts so you can find which ones are wrong: https://www.tumblr.com/blog/dajotim937

_Originally posted by @dajotim937 in https://github.com/TumblThreeApp/TumblThree/issues/196#issuecomment-995436719_

**Comment by thomas694** [comment]
It seems like gifv files aren't downloaded properly.

What do you mean by video gets wrong name? At least the video from that blog gets the correct name, or not?

**Comment by dajotim937** [comment]
> What do you mean by video gets wrong name? At least the video from that blog gets the correct name, or not?
So first post that I repost (second from top in my blog) there is photo and video. I setup some filename template. But video gets default name `tumblr_quiv5jcFTf1xg8h61` instead my template.

**Comment by thomas694** [comment]
> Also gifv are downloading when I'm using SVC downloader instead of API. And for multiboot2.tumblr.com API downloader download only 71 content files and SVC 277. Should I use SVC for all blogs?

Normally when adding a blog the crawler type is automatically chosen. This one is a hidden/dashboard blog, so only the SVC crawler is the correct one, although the API crawler can still download a few posts.

**Comment by dajotim937** [comment]
Testet a bit more:
Gifv not downloading on my `https://www.tumblr.com/blog/dajotim937` blog with SVC and downloading with API. So reverse situation compared to multiboot2 blog.

Also there some date offset problem I guess.
1. Download `https://dajotim937.tumblr.com/` with first downloader (any of both).
2. Close program, delete Index folder (where data for blog are saved)
3. Open program, add blog again, change download folder from `*\dajotim937_2` to `*\dajotim937`
4. Select second downloader and start download.
5. Got 2 files that both have copies.
With template `%b_%d_%i_%f` for first reblogged post (second in blog from top) I got:
`dajotim937_20211215_670700556366626816_d1c856d5d8e62d9445a20ec7faf2a0a98866cd84.jpg` and
`dajotim937_20211216_670700556366626816_d1c856d5d8e62d9445a20ec7faf2a0a98866cd84.jpg` for pics;
And
`dajotim937_20211215_670700556366626816_tumblr_quiv5jcFTf1xg8h61_frame1.jpg`
`dajotim937_20211216_670700556366626816_tumblr_quiv5jcFTf1xg8h61_frame1.jpg` for pic of first video frame.

**Comment by thomas694** [comment]
The background for the behavior you have seen is the following. I'm neither saying wrong or correct, that depends.

You download a "new" blog into an existing folder and expect that nothing new is downloaded as the media files are already there. I haven't tested if changing the crawler/downloader type really changes the outcome, but changing the input parameters (settings) might not produce the same output.
One reason is you did the tests on two different days. The link was not downloaded before (deleted index folder), but then the filename got the current date (%d argument). In normal cases the link is recognized as duplicate and no download is done in the first place.
Another reason is that the second post has the format of a "regular" (text) post, yes, it's a reblog, but the "source" has the same style/type. The images and video are placed as html inside a "regular body" field. In that case the properties of the post are not totally/correctly inherited therefore taking the current date. I think we should change something there.

**Comment by dajotim937** [comment]
`but changing the input parameters (settings) might not produce the same output.`
What input parameters do you mean? I changed only type downloader for same 2 posts. %d should be changed because post date doesn't change.
`One reason is you did the tests on two different days.`
My blog for tests is small, so tested almost in same minute.
Looks like crawlers are using different response date field.
This is text.txt output from API:
```
Post id: 670700556366626816
Date: Wed, 15 Dec 2021 23:44:54
Post url: https://dajotim937.tumblr.com/post/670700556366626816
Slug: 
Reblog key: 8gby3HUo
Reblog url: https://multiboot2.tumblr.com/post/655913565144907776
Reblog name: multiboot2
Title: 
<p><a class="tumblr_blog" href="https://celeb-mix2-and-germans.tumblr.com/post/653671368827846656">celeb-mix2-and-germans</a>:</p><blockquote><figure class="tmblr-full" data-orig-height="878" data-orig-width="396"><img src="https://64.media.tumblr.com/69395ed5f744647e810b366d2eda284b/3d369b4a784e2a73-b8/s640x960/d1c856d5d8e62d9445a20ec7faf2a0a98866cd84.jpg" data-orig-height="878" data-orig-width="396"/></figure><figure class="tmblr-full" data-orig-height="932" data-orig-width="586" data-npf='{"type":"video","provider":"tumblr","url":"https://va.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61.mp4","media":{"url":"https://va.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61.mp4","type":"video/mp4","width":586,"height":932},"poster":[{"url":"https://64.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61_frame1.jpg","type":"image/jpeg","width":586,"height":932}],"filmstrip":{"url":"https://64.media.tumblr.com/previews/tumblr_quiv5jcFTf1xg8h61_filmstrip.jpg","type":"image/jpeg","width":2000,"height":317}}'><video controls="controls" autoplay="autoplay" muted="muted" poster="https://64.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61_frame1.jpg"><source src="https://va.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61.mp4" type="video/mp4"></source></video></figure></blockquote>
Tags: 
```
And this is from SVC:
```
Post id: 670700556366626816
Date: 2021-12-16 04:44:54 GMT
Post url: https://dajotim937.tumblr.com/post/670700556366626816
Slug: 
Reblog key: 8gby3HUo
Reblog url: https://multiboot2.tumblr.com/post/655913565144907776
Reblog name: multiboot2
Summary: 
Title: 
<p><a class="tumblr_blog" href="https://celeb-mix2-and-germans.tumblr.com/post/653671368827846656">celeb-mix2-and-germans</a>:</p><blockquote><figure class="tmblr-full" data-orig-height="878" data-orig-width="396"><img src="https://64.media.tumblr.com/69395ed5f744647e810b366d2eda284b/3d369b4a784e2a73-b8/s640x960/d1c856d5d8e62d9445a20ec7faf2a0a98866cd84.jpg" data-orig-height="878" data-orig-width="396"/></figure><figure class="tmblr-full" data-orig-height="932" data-orig-width="586" data-npf='{"type":"video","provider":"tumblr","url":"https://va.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61.mp4","media":{"url":"https://va.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61.mp4","type":"video/mp4","width":586,"height":932},"poster":[{"url":"https://64.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61_frame1.jpg","type":"image/jpeg","width":586,"height":932}],"filmstrip":{"url":"https://64.media.tumblr.com/previews/tumblr_quiv5jcFTf1xg8h61_filmstrip.jpg","type":"image/jpeg","width":2000,"height":317}}'><video controls="controls" autoplay="autoplay" muted="muted" poster="https://64.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61_frame1.jpg"><source src="https://va.media.tumblr.com/tumblr_quiv5jcFTf1xg8h61.mp4" type="video/mp4"></source></video></figure></blockquote>
Tags: 
```
And there https://dajotim937.tumblr.com/api/read is several fields for post. I guess one downloader is using date-gmt/timestamp and other is using regular date field.
`date-gmt="2021-12-16 04:44:54 GMT" date="Wed, 15 Dec 2021 23:44:54" unix-timestamp="1639629894"`
So i rebloged one more post and for my current time zone +2 date-gmt/timestamp are correct ones for post date in current blog.

**Comment by thomas694** [comment]
Thanks for your additional tests and information.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by AlexFundorin** [comment]
Sorry for offtopic, but how do I convert gifv, which seems to be mp4 video in webp format, to a regular mp4? Batch convert, preferably, or automatically, by TumblThree, when downloading.

**Comment by thomas694** [comment]
The question would be, what gifv file are you talking about? One downloaded by TumblThree and served from their servers, one served from external link, or one saved from browser?
Afaik, the first is already the original gif, only with 'wrong' file extension. So, any tool that can rename from gifv to gif would be suitable. But as you speak of webp it's either 2 or 3.
If necessary and you have a safe example post, you can post it here.

**Comment by dajotim937** [comment]
> The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

Hi. Still get this error, last build version. Api response is `"date-gmt": "2021-12-26 23:58:26 GMT","date": "Sun, 26 Dec 2021 18:58:26"` but some how %d in filename 20211227.

**Comment by thomas694** [comment]
@dajotim937 
That means the poster is living in respectively the blog's time zone is set to US east coast time, while you are living east of GMT, isn't it?
If you are living west of GMT, you can expect this file to be shown on 26, east of GMT on 27. If you change the time zone of your PC to GMT-5 your file should show the date like `Sun, 26 Dec 2021 18:58:26`.

**Comment by dajotim937** [comment]
> That means the poster is living in respectively the blog's time zone is set to US east coast time, while you are living east of GMT, isn't it?

Well maybe, but that doesn't answer why filename contain 20211227 date, if it should use GTM date and GMT is 2021-12-27.
Doesn't this [commit](https://github.com/TumblThreeApp/TumblThree/commit/687d9b3b25554113ae3e4959ca8eb8e9c7849de8) says that `Now always GMT time is used.`?

**Comment by thomas694** [comment]
Ok, maybe now I understand what you expect. You would expect that the filename uses GMT and the file time in explorer is shown in local time (as that's the way windows handles it), right?
No, that commit uses now the GMT time field as original value (before sometimes GMT, sometimes local) and it's used for setting the file's time and creating the filename part, at the end both showing in local time.

I think that's a tricky question. Should the filenames be in GMT, so that everyone on the world creates the same names, even so the majority of the time the filename and the displayed file time differ, or should the filenames be in local time, so that they are 'equal' to this single user.
Before the filename template, there was only the file time and windows (by design) shows it in local time. I think I just kept this pattern without thinking to much on GMT standardization.

Whoever has an opinion might throw it in.

**Comment by dajotim937** [comment]
> You would expect that the filename uses GMT and the file time in explorer is shown in local time (as that's the way windows handles it), right?

~~Don't really understand about the file time in explorer. I talk about only date in filename, where template for name with %d key should replaced by GMT time.~~ Reread your sentence. The file time part confused me, because as for me, it doesn't really matter which time is using in file time attribute. Didn't even think about it. Well, I think yes, that behavior I would expect.
> at the end both showing in local time.

 Oh, okay. Didn't understand that.
> Should the filenames be in GMT, so that everyone on the world creates the same names, even so the majority of the time the filename and the displayed file time differ, or should the filenames be in local time, so that they are 'equal' to this single user.

I prefer GMT in filenames. You could add new key in filename template and specify that %d is using converted time to current timezone and other is using GMT without converting.

Maybe you or I should create new issue, because for new users who check issues it isn't clear that this one ended with time\timezone question. Don't know if you can move some posts to other issue thread.
